run:
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

linters:
  disable:
    - unused

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  new: false
  exclude-use-default: false
